"use client";

import { useState } from "react";
import { marked } from "marked";
import { Card } from "@/components/ui/Card";
import { inputClass, primaryButtonClass } from "@/components/ui/Field";

type ChatMessage = { role: "user" | "model"; text: string };

const STARTER_QUESTIONS = [
  "What setups work best at what time?",
  "What doesn't work on Mondays?",
  "Where does my psychology hurt me most?",
];

export function InsightsChatPanel({ tradeCount }: { tradeCount: number }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function sendMessage(text: string) {
    if (!text.trim() || pending) return;
    const nextMessages: ChatMessage[] = [...messages, { role: "user", text }];
    setMessages(nextMessages);
    setInput("");
    setError(null);
    setPending(true);

    try {
      const res = await fetch("/api/trading/insights-chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: nextMessages }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? "Something went wrong.");
        return;
      }
      setMessages([...nextMessages, { role: "model", text: data.reply }]);
    } catch {
      setError("Couldn't reach the AI service. Try again shortly.");
    } finally {
      setPending(false);
    }
  }

  return (
    <Card accent>
      <h2 className="mb-1 text-lg font-semibold">Ask your trade data</h2>
      <p className="mb-4 text-sm text-neutral-500">
        Answers are generated by AI from your logged Futures &amp; Metals trades — verify anything
        important.
      </p>

      {tradeCount === 0 ? (
        <p className="text-sm text-neutral-500">
          Log some Futures &amp; Metals trades first — there&apos;s no data yet to analyze.
        </p>
      ) : (
        <>
          <div className="mb-3 flex flex-wrap gap-2">
            {STARTER_QUESTIONS.map((q) => (
              <button
                key={q}
                type="button"
                onClick={() => sendMessage(q)}
                disabled={pending}
                className="rounded-full border border-neutral-800 px-3 py-1 text-xs text-neutral-300 transition hover:border-violet-500 hover:text-violet-300 disabled:opacity-50"
              >
                {q}
              </button>
            ))}
          </div>

          {messages.length > 0 && (
            <div className="mb-3 max-h-96 space-y-3 overflow-y-auto">
              {messages.map((m, i) =>
                m.role === "user" ? (
                  <div
                    key={i}
                    className="ml-auto max-w-[85%] rounded-lg bg-violet-600/20 px-3 py-2 text-sm text-neutral-50"
                  >
                    {m.text}
                  </div>
                ) : (
                  <div
                    key={i}
                    className="prose prose-invert prose-sm max-w-none rounded-lg border border-neutral-800 bg-neutral-900/50 px-3 py-2 prose-p:text-neutral-300 prose-li:text-neutral-300"
                    dangerouslySetInnerHTML={{ __html: marked.parse(m.text, { async: false }) as string }}
                  />
                ),
              )}
              {pending && <p className="text-sm text-neutral-500">Thinking…</p>}
            </div>
          )}

          {error && <p className="mb-2 text-sm text-red-400">{error}</p>}

          <form
            onSubmit={(e) => {
              e.preventDefault();
              sendMessage(input);
            }}
            className="flex gap-2"
          >
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="e.g. what doesn't work on Mondays?"
              className={inputClass}
              disabled={pending}
            />
            <button type="submit" className={primaryButtonClass} disabled={pending || !input.trim()}>
              Ask
            </button>
          </form>
        </>
      )}
    </Card>
  );
}
