import { callGemini } from "@/lib/core/gemini";

const SYSTEM_PROMPT = `
You help a solo Etsy seller brainstorm Midjourney prompts for AI-generated wall-art posters.

You may do cautious public research (general knowledge of visual trends, cultural/travel themes,
seasonality) to inform the ideas, but you have NO access to private Etsy sales data, competitor
conversion rates, Etsy search volume, eRank, Marmalead, or any tool that reveals real demand or
competition. Never claim or imply access to any of that. Never promise guaranteed low competition
or guaranteed sales — public evidence is not proof of demand.

For each prompt, describe standalone wall-art artwork (not a product photo, not a mockup). The
scene must read as edge-to-edge and borderless: details should continue naturally beyond all four
edges, with content in every corner, and there must be no frame, border, margin, matting, wall
mockup, paper edge, watermark, or unwanted typography described in the scene.

Respond with ONLY a JSON object, no markdown fences, no commentary, matching exactly:
{
  "researchSummary": "1-3 sentences on what informed these ideas, or empty string if none",
  "sources": ["plain-text source description, e.g. a general trend or theme — no fabricated URLs"],
  "confidence": "low" | "medium" | "high",
  "limitations": "1-2 sentences on what this research does NOT tell you (e.g. no real demand data)",
  "prompts": [
    { "sceneDescription": "the creative scene/subject description only — no aspect ratio or composition instructions, those are added separately" }
  ]
}

The "prompts" array must contain exactly the number of items requested.
`.trim();

export interface GeneratedPromptDraft {
  sceneDescription: string;
}

export interface PromptStudioResult {
  researchSummary: string;
  sources: string[];
  confidence: string;
  limitations: string;
  prompts: GeneratedPromptDraft[];
}

const CHUNK_SIZE = 5;

/**
 * Generates `count` prompt drafts, chunking into bounded requests so a single
 * large/fragile AI response can't take down the whole batch. Each chunk is
 * independent — a failed chunk doesn't lose prompts already generated by an
 * earlier chunk (the caller persists incrementally, chunk by chunk).
 */
export async function generatePromptDrafts(collectionRequest: string, count: number): Promise<PromptStudioResult> {
  const chunks: number[] = [];
  let remaining = count;
  while (remaining > 0) {
    const size = Math.min(CHUNK_SIZE, remaining);
    chunks.push(size);
    remaining -= size;
  }

  const results: PromptStudioResult[] = [];
  for (const size of chunks) {
    results.push(await generateChunk(collectionRequest, size));
  }

  return {
    researchSummary: results[0]?.researchSummary ?? "",
    sources: [...new Set(results.flatMap((r) => r.sources))],
    confidence: results[0]?.confidence ?? "low",
    limitations: results[0]?.limitations ?? "",
    prompts: results.flatMap((r) => r.prompts),
  };
}

async function generateChunk(collectionRequest: string, count: number): Promise<PromptStudioResult> {
  const raw = await callGemini(SYSTEM_PROMPT, [
    {
      role: "user",
      parts: [{ text: `Collection brief: ${collectionRequest}\n\nGenerate exactly ${count} distinct prompt ideas.` }],
    },
  ]);

  const cleaned = raw.trim().replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```\s*$/i, "");
  const parsed = JSON.parse(cleaned);

  const prompts: GeneratedPromptDraft[] = Array.isArray(parsed.prompts)
    ? parsed.prompts
        .filter((p: unknown) => p && typeof (p as { sceneDescription?: unknown }).sceneDescription === "string")
        .map((p: { sceneDescription: string }) => ({ sceneDescription: p.sceneDescription.trim() }))
    : [];

  if (prompts.length === 0) {
    throw new Error("Gemini returned no usable prompts for this chunk");
  }

  return {
    researchSummary: String(parsed.researchSummary ?? ""),
    sources: Array.isArray(parsed.sources) ? parsed.sources.map(String) : [],
    confidence: String(parsed.confidence ?? "low"),
    limitations: String(parsed.limitations ?? ""),
    prompts,
  };
}

/**
 * Deterministically wraps a scene description into the mandatory borderless
 * composition instructions and the aspect-ratio suffix — never trusts the AI
 * to have included these correctly. Applying this to an older prompt (e.g.
 * when copying one) re-applies the current protection even if the stored
 * text predates a wording change here.
 */
export function normalizePromptText(sceneDescription: string, aspectRatio: string): string {
  const scene = sceneDescription.trim().replace(/\s+/g, " ");
  return (
    `${scene}, edge-to-edge composition with details continuing beyond all four edges, ` +
    `content in every corner, no frame, no border, no margin, no matting, no wall mockup, ` +
    `no paper edge, no watermark, no typography --ar ${aspectRatio}`
  );
}
